# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bm < Formula
  desc "Your command-line sidekick for teleporting to files, folders, and URLs in one hop."
  homepage "https://github.com/Shu-AFK/bm"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Shu-AFK/bm/releases/download/v0.3.1/bm_0.3.1_darwin_amd64.tar.gz"
      sha256 "64727b92e2473c45c8875893fbcded21389e22dfbfb6c4cf4796889290f7814a"

      def install
        bin.install "bm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Shu-AFK/bm/releases/download/v0.3.1/bm_0.3.1_darwin_arm64.tar.gz"
      sha256 "369118ed860307e37f2aa62d06ebdc0050b2f9aa58707f9877614a3a963e17eb"

      def install
        bin.install "bm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Shu-AFK/bm/releases/download/v0.3.1/bm_0.3.1_linux_amd64.tar.gz"
      sha256 "ac9d4216273bb12364795fc3bdf02f0c18c59cd859b41741cea64bfe4bdd2d1b"
      def install
        bin.install "bm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Shu-AFK/bm/releases/download/v0.3.1/bm_0.3.1_linux_arm64.tar.gz"
      sha256 "9bf71a0eb9ea7fd09a605ac9ad619559b2a69ef9d34e9425f0db2a17d4a69185"
      def install
        bin.install "bm"
      end
    end
  end

  test do
    system "#{bin}/bm", "--version"
  end
end
