# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bm < Formula
  desc "Your command-line sidekick for teleporting to files, folders, and URLs in one hop."
  homepage "https://github.com/Shu-AFK/bm"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Shu-AFK/bm/releases/download/v0.2.0/bm_0.2.0_darwin_amd64.tar.gz"
      sha256 "75980e02497f9947a706813711796175f22e743da97567ad66ae0a97d33d4eec"

      def install
        bin.install "bm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Shu-AFK/bm/releases/download/v0.2.0/bm_0.2.0_darwin_arm64.tar.gz"
      sha256 "b16a798fb6ad4a9626ed4cc212efb1efad17ee6af944f23cc8c98328b8e044d4"

      def install
        bin.install "bm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Shu-AFK/bm/releases/download/v0.2.0/bm_0.2.0_linux_amd64.tar.gz"
      sha256 "2cfe2fabe61b7f6e5543d965f8da540bf8619c6cf15ddecd1d6d3b9440e6fa87"
      def install
        bin.install "bm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Shu-AFK/bm/releases/download/v0.2.0/bm_0.2.0_linux_arm64.tar.gz"
      sha256 "c8c5c257724242078a67452cc567642fb45ecd34af20ed198f04b6dca84654ae"
      def install
        bin.install "bm"
      end
    end
  end

  test do
    system "#{bin}/bm", "--version"
  end
end
